### ISSUE TITLE
Linked Styleguide not Generated in Project

### ISSUE THREAD

**Issue by b-wils** [novemberfiveco/zeplin-styled-components#5]
This extensions it not generating the styleguide if I am in a project that uses a linked styleguide. This is not a big deal since I can go straight to the guide to get the styles. Is this expected? 
<img width="1273" alt="Screen Shot 2019-07-31 at 1 42 22 PM" src="https://user-images.githubusercontent.com/1399576/62241434-c4d4dd00-b39e-11e9-87c3-f928ffcf7844.png">

**Comment by nickverstocken** [comment]
Hi! 
This is because of the new update of Zeplin and I haven't found the time to update the extension to support global styles. I will fix this some time next week! Will keep you posted!
